import swaggerJsdoc from 'swagger-jsdoc';

const options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'API de Gestión de Parqueadero',
      version: '0.1.0',
    },
    servers: [{ url: '/api/v1' }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        Celda: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            codigo: { type: 'string', example: 'A-12' },
            zona: { type: 'string', example: 'Zona A' },
            tipoPermitido: { type: 'string', enum: ['CARRO', 'MOTO', 'BICICLETA', 'OTRO'] },
            estado: { type: 'string', enum: ['LIBRE', 'OCUPADA', 'MANTENIMIENTO'] },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Usuario: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            nombre: { type: 'string' },
            email: { type: 'string', format: 'email' },
            rol: { type: 'string', enum: ['ADMIN', 'OPERADOR'] },
            activo: { type: 'boolean' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Vehiculo: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            placa: { type: 'string', example: 'ABC123' },
            tipo: { type: 'string', enum: ['CARRO', 'MOTO', 'BICICLETA', 'OTRO'] },
            propietarioNombre: { type: 'string', nullable: true },
            propietarioTelefono: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Turno: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            operadorId: { type: 'string', format: 'uuid' },
            apertura: { type: 'string', format: 'date-time' },
            cierre: { type: 'string', format: 'date-time', nullable: true },
            baseInicial: { type: 'integer' },
            totalRecaudado: { type: 'integer', nullable: true },
            efectivoContado: {
              type: 'integer',
              nullable: true,
              description: 'Solo se llena al cerrar el turno',
            },
            efectivoEsperado: {
              type: 'integer',
              nullable: true,
              description: 'Solo se llena al cerrar el turno',
            },
            diferencia: {
              type: 'integer',
              nullable: true,
              description: 'Sobrante > 0, faltante < 0, cuadre exacto = 0. Solo se llena al cerrar el turno',
            },
            estado: { type: 'string', enum: ['ABIERTO', 'CERRADO'] },
          },
        },
        ArqueoTurno: {
          type: 'object',
          description: 'Resumen de caja de un turno, parcial (ABIERTO) o final (CERRADO).',
          properties: {
            turnoId: { type: 'string', format: 'uuid' },
            operadorId: { type: 'string', format: 'uuid' },
            estado: { type: 'string', enum: ['ABIERTO', 'CERRADO'] },
            apertura: { type: 'string', format: 'date-time' },
            cierre: { type: 'string', format: 'date-time', nullable: true },
            baseInicial: { type: 'integer' },
            totalesPorMetodo: {
              type: 'object',
              properties: {
                EFECTIVO: { type: 'integer' },
                TARJETA: { type: 'integer' },
                TRANSFERENCIA: { type: 'integer' },
              },
            },
            totalRecaudado: { type: 'integer' },
            ticketsCerrados: { type: 'integer' },
            efectivoEsperado: { type: 'integer' },
            efectivoContado: {
              type: 'integer',
              nullable: true,
              description: 'null mientras el turno sigue ABIERTO: todavía no se ha contado caja',
            },
            diferencia: {
              type: 'integer',
              nullable: true,
              description: 'Sobrante > 0, faltante < 0, cuadre exacto = 0. null mientras el turno sigue ABIERTO',
            },
          },
        },
        Pago: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            ticketId: { type: 'string', format: 'uuid', nullable: true },
            mensualidadId: { type: 'string', format: 'uuid', nullable: true },
            monto: { type: 'integer' },
            metodo: { type: 'string', enum: ['EFECTIVO', 'TARJETA', 'TRANSFERENCIA'] },
            turnoId: { type: 'string', format: 'uuid' },
            fecha: { type: 'string', format: 'date-time' },
            estado: { type: 'string', enum: ['VALIDO', 'ANULADO'] },
          },
        },
        Tarifa: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            tipoVehiculo: { type: 'string', enum: ['CARRO', 'MOTO', 'BICICLETA', 'OTRO'] },
            valorMinuto: { type: 'integer' },
            valorPlena: { type: 'integer' },
            valorNocturna: { type: 'integer' },
            valorMes: { type: 'integer' },
            vigenteDesde: { type: 'string', format: 'date-time' },
            vigenteHasta: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        HorarioOperacion: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            apertura: { type: 'string', example: '08:00', description: 'Hora local, formato HH:mm' },
            cierre: { type: 'string', example: '21:30', description: 'Hora local, formato HH:mm' },
            vigenteDesde: { type: 'string', format: 'date-time' },
            vigenteHasta: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Mensualidad: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            vehiculoId: { type: 'string', format: 'uuid' },
            celdaId: { type: 'string', format: 'uuid', nullable: true },
            fechaInicio: { type: 'string', format: 'date-time' },
            fechaFin: { type: 'string', format: 'date-time' },
            valorMensualidad: { type: 'integer' },
            estadoPago: { type: 'string', enum: ['PAGADA', 'NO_PAGADA', 'CANCELADA'] },
            fechaPago: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Establecimiento: {
          type: 'object',
          properties: {
            nombre: { type: 'string', example: 'Parqueadero Ejemplo S.A.S.' },
            nit: { type: 'string', example: '900.123.456-7' },
            direccion: { type: 'string' },
            telefono: { type: 'string' },
            ciudad: { type: 'string' },
            regimenTributario: { type: 'string' },
            numeroResolucion: { type: 'string' },
            textoResponsabilidad: { type: 'string' },
            textoSeguro: { type: 'string' },
            textoHorario: { type: 'string' },
            textoReclamos: { type: 'string' },
          },
        },
        Recibo: {
          type: 'object',
          description: 'Recibo listo para imprimir; null si el ticket sigue ABIERTO.',
          nullable: true,
          properties: {
            consecutivo: { type: 'integer', example: 1024 },
            fechaEmision: { type: 'string', format: 'date-time' },
            establecimiento: { $ref: '#/components/schemas/Establecimiento' },
            placa: { type: 'string', example: 'ABC123' },
            tipoVehiculo: { type: 'string', enum: ['CARRO', 'MOTO', 'BICICLETA', 'OTRO'] },
            celda: { type: 'string', example: 'A-12' },
            horaEntrada: { type: 'string', format: 'date-time' },
            horaSalida: { type: 'string', format: 'date-time' },
            tiempoTotal: { type: 'string', example: '1h 30min' },
            desglose: { type: 'array', items: { type: 'object' } },
            total: { type: 'integer' },
            metodoPago: {
              type: 'string',
              enum: ['EFECTIVO', 'TARJETA', 'TRANSFERENCIA'],
              nullable: true,
            },
            operador: { type: 'string', nullable: true },
          },
        },
        Ticket: {
          type: 'object',
          properties: {
            id: { type: 'string', format: 'uuid' },
            codigo: { type: 'string', example: 'T-260818-A3F91C' },
            vehiculoId: { type: 'string', format: 'uuid' },
            celdaId: { type: 'string', format: 'uuid' },
            horaEntrada: { type: 'string', format: 'date-time' },
            horaSalida: { type: 'string', format: 'date-time', nullable: true },
            tarifaId: { type: 'string', format: 'uuid' },
            horarioId: { type: 'string', format: 'uuid' },
            valorTotal: { type: 'integer', nullable: true },
            desglose: { type: 'array', items: { type: 'object' }, nullable: true },
            estado: { type: 'string', enum: ['ABIERTO', 'PAGADO', 'ENTREGADO', 'ANULADO'] },
            operadorEntradaId: { type: 'string', format: 'uuid' },
            operadorSalidaId: { type: 'string', format: 'uuid', nullable: true },
            motivoAnulacion: { type: 'string', nullable: true },
            anuladoPorId: { type: 'string', format: 'uuid', nullable: true },
            anuladoEn: { type: 'string', format: 'date-time', nullable: true },
            entregadoPorId: { type: 'string', format: 'uuid', nullable: true },
            entregadoEn: { type: 'string', format: 'date-time', nullable: true },
            reciboConsecutivo: { type: 'integer', nullable: true },
            vehiculo: { $ref: '#/components/schemas/Vehiculo' },
            celda: { $ref: '#/components/schemas/Celda' },
            pago: { $ref: '#/components/schemas/Pago' },
            operadorSalida: { $ref: '#/components/schemas/Usuario' },
            recibo: { $ref: '#/components/schemas/Recibo' },
          },
        },
        Error: {
          type: 'object',
          properties: {
            error: {
              type: 'object',
              properties: {
                code: { type: 'string' },
                message: { type: 'string' },
                details: { type: 'array', items: { type: 'object' } },
              },
            },
          },
        },
      },
    },
  },
  apis: ['./src/routes/*.routes.js'],
};

export const openapiSpec = swaggerJsdoc(options);
